#spring:
#  application:
#    name: challenge-java-developer
#
#  datasource:
#      url: jdbc:postgresql://localhost:5432/db_neurotec_challenge
#      driver-class-name: org.postgresql.Driver
#      username: postgres
#      password: admin
#
#server:
#  port: 5000
#
#  # jpa
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#        format_sql: true
#        show_sql: true
#    hibernate:
#      ddl-auto: update